Fix inconsistency in properties' names
ga4gh-beacon/specification-v2 pull request #75
Opened 2021-05-21 10:51 UTC by sdelatorrep

They should start with lowercase to keep consistency among all properties.

2021-05-21 10:56 UTC, sdelatorrep commented
@redmitry, I can't add you as a reviewer, but, as you were the first noticing this inconsistency, you may want to take a look. Thanks! :)

2021-05-21 11:08 UTC, mbaudis approved these changes

2021-05-28 06:27 UTC, mbaudis commented on beacon.yaml
> +        filterTerm:
filterTerm => filteringTerm

2021-05-28 06:28 UTC, mbaudis requested changes
See note on line 1255; should be "filteringTerm". Otherwise ok.

2021-06-04 11:02 UTC, sdelatorrep commented on beacon.yaml
> +        filterTerm:
Done!

2021-06-04 11:06 UTC, mbaudis approved these changes

2021-06-04 11:11 UTC, merged